#ifndef _HTTP_COMMON__H_
#define _HTTP_COMMON__H_

#include "sstr.h"
#include "URI.h"

SSTREXTRN(HTTP_STATUS_200);

SSTREXTRN(HTTP_STATUS_300);
SSTREXTRN(HTTP_STATUS_301);
SSTREXTRN(HTTP_STATUS_302);
SSTREXTRN(HTTP_STATUS_303);
SSTREXTRN(HTTP_STATUS_304);

SSTREXTRN(HTTP_STATUS_400);
SSTREXTRN(HTTP_STATUS_403);
SSTREXTRN(HTTP_STATUS_404);
SSTREXTRN(HTTP_STATUS_411);

SSTREXTRN(HTTP_STATUS_500);
SSTREXTRN(HTTP_STATUS_501);
SSTREXTRN(HTTP_STATUS_503);

SSTREXTRN(HTTP_CONTENT_TYPE_TEXT_PLAIN);
SSTREXTRN(HTTP_CONTENT_TYPE_TEXT_XML);
SSTREXTRN(HTTP_CONTENT_TYPE_TEXT_HTML);
SSTREXTRN(HTTP_CONTENT_TYPE_JSON);
SSTREXTRN(HTTP_CONTENT_TYPE_IMAGE_GIF);

SSTREXTRN(HTTP_SET_COOKIE);

#endif // _HTTP_COMMON__H_


